
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.border.LineBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class welcomepage extends javax.swing.JFrame {
   
    

    /**
     * Creates new form welcomepage
     */
    public welcomepage() {
        initComponents();
        addp.searchBox("", jtb);
         refreshQuantity.start();
        checkLowQuantitys.start();
        
    }
    
    public welcomepage(String uname){
        initComponents();
         addp.searchBox("", jtb);
         refreshQuantity.start();
        checkLowQuantitys.start(); 
        
        
        
    }
    String getProdname(){
        return search_tf.getText();
    }
    
    
product addp=new product();
connt cons = new connt();  
int id=0;



public void clearp(){
    
    add_prod.setText("");
   prod_quant.setValue(0);
    prod_price.setText("");
    
}
public void pp(){
    
    String prodname=add_prod.getText();
    int quant=(int) prod_quant.getValue();
    Float pprice=Float.parseFloat(prod_price.getValue().toString());
    addp.addproduct1(prodname, quant, pprice);
    JOptionPane.showMessageDialog(addproduct, "Successfull Added");
   
    //JOptionPane.showMessageDialog(rootPane, "done!");
    
    
}


final void refreshQuantitys(String prodname) {
    
        try {
            Class.forName("com.mysql.jdbc.Driver");
            com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(cons.url, cons.username, cons.password);

            String sql = "SELECT Prod_quantity FROM product WHERE Prod_ID LIKE ? OR Prod_name LIKE ? ";
            com.mysql.jdbc.PreparedStatement pstmt = (com.mysql.jdbc.PreparedStatement) conn.prepareStatement(sql);

            pstmt.setString(1, "%" + prodname + "%");
            pstmt.setString(2, "%" + prodname + "%");
            
            ResultSet rs = pstmt.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel) jtb.getModel();
            int row = 0;
            while (rs.next()) {
                int quantity = rs.getInt("Prod_quantity");
                //model.addRow(new Object[]{rs.getString("id"), rs.getString("product_name"), rs.getString("quantity"), rs.getString("price")});
                model.setValueAt(quantity, row, 2);
                row++;
            }

        }  catch (ClassNotFoundException ex) {
            Logger.getLogger(welcomepage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(welcomepage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

 Thread refreshQuantity = new Thread(new Runnable(){
            
            @Override
            public void run(){
                try{
                    while(true){
                        refreshQuantitys(getProdname());
                        Thread.sleep(1000);
                    }                  
                } catch (InterruptedException ex) {
                    Logger.getLogger(welcomepage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            });
 
 Thread checkLowQuantitys = new Thread(new Runnable(){
       Notification ns = new Notification();
       @Override
       public void run(){
           try{
               while(true){
                   ns.checkLowProduct();
                   Thread.sleep(1000);
               }
           } catch (InterruptedException ex) {
               Logger.getLogger(welcomepage.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    });


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addproduct = new javax.swing.JFrame();
        prod_price = new javax.swing.JFormattedTextField();
        prod_quant = new javax.swing.JSpinner();
        add_prod = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        addp_label = new javax.swing.JLabel();
        editbtn = new javax.swing.JButton();
        addqtybtn = new javax.swing.JButton();
        currentqty = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        search_tf = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        addproduct.setMinimumSize(new java.awt.Dimension(400, 320));

        prod_price.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        prod_price.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        prod_quant.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));

        add_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_prodActionPerformed(evt);
            }
        });

        jLabel12.setText("Productname:");

        jLabel13.setText("Quantity:");

        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        jLabel14.setText("Price:");

        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        addp_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addp_label.setText("Add Product");

        editbtn.setText("Save");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        addqtybtn.setText("Add Quantity");
        addqtybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addqtybtnActionPerformed(evt);
            }
        });

        currentqty.setText("jLabel2");

        javax.swing.GroupLayout addproductLayout = new javax.swing.GroupLayout(addproduct.getContentPane());
        addproduct.getContentPane().setLayout(addproductLayout);
        addproductLayout.setHorizontalGroup(
            addproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addproductLayout.createSequentialGroup()
                .addGroup(addproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(addp_label))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(addproductLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(addproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addproductLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(currentqty, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prod_quant, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addproductLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addproductLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGroup(addproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addproductLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prod_price, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addproductLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(addproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addqtybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(43, 43, 43)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        addproductLayout.setVerticalGroup(
            addproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addproductLayout.createSequentialGroup()
                .addComponent(addp_label)
                .addGap(45, 45, 45)
                .addGroup(addproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentqty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prod_quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addGap(30, 30, 30)
                .addGroup(addproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prod_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(28, 28, 28)
                .addComponent(addbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addqtybtn)
                .addGap(10, 10, 10)
                .addComponent(jButton2))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCT", "QUANTITY", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtb);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("WELCOME!");

        jButton1.setText("AddProduct");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Edit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        search_tf.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        search_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_tfActionPerformed(evt);
            }
        });
        search_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_tfKeyReleased(evt);
            }
        });

        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Add Quantity");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_prodActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_add_prodActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        //String prodname=add_prod.getText();
        //int quant=(int) prod_quant.getValue();
        //float price=(float) prod_price.getValue();

       // addp.addproduct(prodname, quant, price);
        pp();addp.searchBox("", jtb);; clearp();
        //if(!"".equals(prodname)&& !"".equals(quant)&& !"".equals(price)){
         //   JOptionPane.showMessageDialog(addproduct,"Please Fill up All Fields");
        //}else{
          //  addp.addproduct(prodname, quant, price);
          //  JOptionPane.showMessageDialog(addproduct, "Successfully");
       // }

        // TODO add your handling code here:
    }//GEN-LAST:event_addbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

addproduct.setVisible(true);
addproduct.setLocationRelativeTo(null);
editbtn.setVisible(false);
addqtybtn.setVisible(false);
currentqty.setEnabled(false);
addproduct.setAlwaysOnTop(true);

add_prod.setText("");
add_prod.setEnabled(true);
prod_quant.setValue(0);
prod_quant.setEnabled(true);
prod_price.setText("");
prod_price.setEnabled(true);

currentqty.setText("");
prod_quant.setEnabled(true);
addp_label.setText("Add Product");
addbtn.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
addproduct.setVisible(false);
this.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     logIn lgf=new logIn();
     lgf.setVisible(true);
     this.setVisible(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int i=jtb.getSelectedRow();
        
        if(i==-1){
            JOptionPane.showMessageDialog(rootPane, "Please Select ROw to Delete");
        }
        else{
            Object id=jtb.getValueAt(i, 0);
            Object prodname=jtb.getValueAt(i, 1);
            
            
            
            int x=JOptionPane.showConfirmDialog(rootPane,"This will Delete  "+prodname+"\nClick Ok to Continue!","Confirm Delete",JOptionPane.OK_CANCEL_OPTION );
            
            if(x==JOptionPane.OK_OPTION){
                
                int xx=JOptionPane.showConfirmDialog(rootPane, "Are you Sure You want to Delete "+prodname+"?","Delete",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
                
                if(xx==JOptionPane.YES_OPTION){
                    
                    int j=addp.Deleteproduct(id);
                    
                    if(j==1){
                        JOptionPane.showMessageDialog(rootPane, "Product "+prodname+" Deleted","Product Deleted",JOptionPane.WARNING_MESSAGE);
                        addp.searchBox("", jtb);
                    }
                }
            }
           
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         //int i=jtb.getSelectedRow();
         add_prod.setEnabled(true);
         add_prod.setText("");
         
         currentqty.setText("");
         addqtybtn.setVisible(false);
         prod_price.setEnabled(true);
         
         
         
         
         int i=jtb.getSelectedRow();
        
        if(i==-1){
            JOptionPane.showMessageDialog(rootPane, "Please Select ROw to Edit");
        }
        else{
            addproduct.setVisible(true);
            addproduct.setLocationRelativeTo(null);
           addproduct.setAlwaysOnTop(true);
            prod_quant.setEnabled(false);
            addp_label.setText("Edit Product");
            addbtn.setVisible(false);
            editbtn.setVisible(true);
            
            
            id=Integer.parseInt(jtb.getValueAt(i, 0).toString());
            
            String pname=jtb.getValueAt(i,1).toString();
            String price=jtb.getValueAt(i, 3).toString();
            int qty =Integer.parseInt( jtb.getValueAt(i, 2).toString());
            
            add_prod.setText(pname);
            prod_quant.setValue(qty);
            prod_price.setText(price);
            
            
            
            }
    
         
        

        // TODO add your handling code here cute c mamai;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        
        String newprodname = add_prod.getText();
        float newprice =Float.parseFloat( prod_price.getValue().toString());
        
        int f = addp.editprod(id, newprodname, newprice);
        
        if(f==1){
            JOptionPane.showMessageDialog(addproduct,"Product Edit Successfully!");
            addproduct.setVisible(false);
            addp.searchBox("", jtb);
            this.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(addproduct, "There Was a Problem Editing Prodcut","ERROR",JOptionPane.ERROR_MESSAGE);
            
        }
        
        
        


        // TODO add your handling code here:
    }//GEN-LAST:event_editbtnActionPerformed

    private void search_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tfActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       // String prodname = search_tf.getText();
       //this.searchBox(prodname);
       

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void search_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_tfKeyReleased
 String prodname = search_tf.getText();
 addp.searchBox(prodname, jtb);
         
// TODO add your handling code here:
    }//GEN-LAST:event_search_tfKeyReleased

    private void addqtybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addqtybtnActionPerformed
            String prdname = add_prod.getText();
            int qty =Integer.parseInt(prod_quant.getValue().toString());
            
            int x = JOptionPane.showConfirmDialog(addproduct,"Add \n"+qty+"\nto "+"''"+prdname+"''"+" ?","Add Quantity",JOptionPane.YES_NO_OPTION);
            
            if(x==JOptionPane.YES_OPTION){
                int c = addp.addQuantity(id, qty);
                if(c==1){
                    JOptionPane.showMessageDialog(addproduct,"Product Quantity Updated!");
                    addproduct.setVisible(false);
                    addp.searchBox("", jtb);
                }
            }
            
           


        // TODO add your handling code here:
    }//GEN-LAST:event_addqtybtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            addp_label.setText("Add Quantity");      
        int row = jtb.getSelectedRow();
        if(row !=-1){
            addproduct.setVisible(true);
            addproduct.setLocationRelativeTo(this);
            addproduct.setAlwaysOnTop(true);
            
            add_prod.setEnabled(false);
            prod_price.setEnabled(false);
            prod_quant.setEnabled(true);
            
            editbtn.setVisible(false);
            addbtn.setVisible(false);
            addqtybtn.setVisible(true);
            
            id=Integer.parseInt(jtb.getValueAt(row, 0).toString());
            String prdname=jtb.getValueAt(row,1).toString();
            String qty= jtb.getValueAt(row,2).toString();
            String pri=jtb.getValueAt(row,3).toString();
            
            add_prod.setText(prdname);
            currentqty.setText(qty);
            prod_price.setText(pri);
            prod_quant.setValue(0);
            
            
            
            
            
        }else{
            JOptionPane.showMessageDialog(rootPane,"Please Select Row");
        }



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcomepage().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add_prod;
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel addp_label;
    private javax.swing.JFrame addproduct;
    private javax.swing.JButton addqtybtn;
    private javax.swing.JLabel currentqty;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtb;
    private javax.swing.JFormattedTextField prod_price;
    private javax.swing.JSpinner prod_quant;
    private javax.swing.JTextField search_tf;
    // End of variables declaration//GEN-END:variables
}
